  jobs:
  - job: DeployJob
    displayName: 'Deploy job-$(ENVIRONMENT)'
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: devops/deploy.ps1
        pwsh: true

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Web App Source code artifact'
      inputs:
        buildType: 'current' 
        artifactName: 'webappsourcecode'
        targetPath: '$(Pipeline.Workspace)/webappsourcecode'

    - task: PowerShell@2
      displayName: 'PowerShell - display contents'
      inputs:
        targetType: 'inline'
        script: |
          dir $(Pipeline.Workspace)
        pwsh: true
