  jobs:
  - job: DeployJob
    displayName: 'Deploy job-$(ENVIRONMENT)'
    steps:

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Web App Source code artifact'
      inputs:
        buildType: 'current' 
        artifactName: 'webappsourcecode'
        targetPath: '$(Pipeline.Workspace)/webappsourcecode'

    - task: PowerShell@2
      displayName: 'Deploy web app $(ENVIRONMENT)'
      inputs:
        targetType: 'filePath'
        filePath: devops/deploy.ps1
        pwsh: true
