  jobs:
  - job: DeployJob
    displayName: 'Deploy job-$(ENVIRONMENT)'
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: devops/deploy.ps1
        pwsh: true
