

variables:
- name: MajorVersion
  value: 1
- name: MinorVersion
  value: 0
- name: PatchNumber
  value: 0

name: $(MajorVersion).$(MinorVersion).$(PatchNumber).$(Rev:r)


stages:
- stage: BUILD
  jobs:
  - job: Build job
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline' # 'filePath' | 'inline'. Type. Default: filePath.
        pwsh: true
        script: | 
          Write-Host "Inside Build task" 
          Write-Host "Displaying environment variables" 
          dir env:


- stage: DEV_DEPLOY
  dependsOn: BUILD
  variables: 
  - name: environment
    value: dev
  jobs:
  - job: Deploy job
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: devops/deploy.ps1
        pwsh: true

- stage: PROD_DEPLOY
  dependsOn: DEV_DEPLOY
  condition: eq(variables['build.sourceBranch'], 'refs/heads/main')
  variables: 
  - name: environment
    value: prod
  jobs:
  - job: Deploy job
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: devops/deploy.ps1
        pwsh: true
