pool:
  vmImage: ubuntu-latest

variables:
- name: MajorVersion
  value: 1
- name: MinorVersion
  value: 0
- name: PatchNumber
  value: 0

name: $(MajorVersion).$(MinorVersion).$(PatchNumber).$(Rev:r)


stages:
- stage: BUILD
  jobs:
  - job: BuildJob
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline' # 'filePath' | 'inline'. Type. Default: filePath.
        pwsh: true
        script: | 
          Write-Host "Inside Build task" 
          Write-Host "Displaying environment variables" 
          dir env:

    - task: ArchiveFiles@2
      displayName: 'Create a ZIP of the Python web app source'
      inputs:
        rootFolderOrFile: 'webfrontend'
        archiveFile: '$(Build.ArtifactStagingDirectory)/webappsourcecode-$(Build.BuildNumber).zip'
        verbose: true

- stage: DEV_DEPLOY
  dependsOn: BUILD
  variables: 
  - name: environment
    value: dev
  jobs:
  - job: DeployJob
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: devops/deploy.ps1
        pwsh: true
    - task: UsePythonVersion@0
      displayName: 'Deploy to DEV'
      inputs:
        versionSpec: '3.9'
        addToPath: true 


- stage: PROD_DEPLOY
  dependsOn: DEV_DEPLOY
  condition: eq(variables['build.sourceBranch'], 'refs/heads/main')
  variables: 
  - name: environment
    value: prod
  jobs:
  - job: DeployJob
    steps:
    - task: PowerShell@2
      displayName: 'Deploy to PROD'
      inputs:
        targetType: 'filePath'
        filePath: devops/deploy.ps1
        pwsh: true
